# -*- coding: utf-8 -*-
"""coronavirus_case_study.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GpQHFDX7_pQzUcBoXx6YTiqufRKvR-Nh
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Get the dataset directly from the source (Kaggle)
!wget -cq https://www.kaggle.com/sudalairajkumar/novel-corona-virus-2019-dataset#2019_nCoV_data.csv

df = pd.read_csv('2019_nCoV_data.csv')

df

df.drop_duplicates(inplace=True)
df

# Remove columns not required for study
df.drop(['Sno','Last Update'], axis=1, inplace=True)

df.head()

# List of affected provinces/states
aff_ps = df['Province/State'].unique()
print(aff_ps)
print(len(aff_ps))

# Number of cases in each State/Province
case_sp = df.groupby('Province/State', as_index=False)[['Confirmed','Deaths','Recovered']].max()
case_sp

# List of affected countries
aff_c = df.Country.unique()
print(aff_c)
print(len(aff_c))

# Number of cases in each Country
case_c = df.groupby(['Country', 'Date']).sum().reset_index()
case_c = case_c.sort_values('Date', ascending=False)
case_c = case_c.drop_duplicates(subset = ['Country'])
case_c.sort_values('Country')[['Country','Confirmed','Deaths','Recovered']].reset_index(drop=True)

